-- ICWT 2026-27 roster seed, generated from ESPN roster pages
-- Safe to re-run: managers/players use WHERE NOT EXISTS guards,
-- teams use ON CONFLICT, roster_entries are cleared and reinserted per team.

-- 1. Season row
insert into seasons (year, season_number)
select 2026, 9
where not exists (select 1 from seasons where year = 2026);

-- 2. Managers (no-op if these names already exist)
insert into managers (name, slug)
select v.name, v.slug from (values
  ('AJ Weine', 'aj-weine'),
  ('Aiden Foreman', 'aiden-foreman'),
  ('Brandon Frankel', 'brandon-frankel'),
  ('Brandon Turofsky', 'brandon-turofsky'),
  ('Danny Schechter', 'danny-schechter'),
  ('Drew Ruchim', 'drew-ruchim'),
  ('Ethan Pestine', 'ethan-pestine'),
  ('Frank Carris', 'frank-carris'),
  ('Jake Freed', 'jake-freed'),
  ('Justin Tumpowsky', 'justin-tumpowsky')
) as v(name, slug)
where not exists (select 1 from managers m where m.name = v.name);

-- 3. Teams for season 2026 (team_name updates if the team row already exists)
insert into teams (season_id, manager_id, team_name)
select s.id, m.id, v.team_name
from (values
  ('Drew Ruchim', 'Catalena Wine Mixer'),
  ('Danny Schechter', 'The Goodnight Streaks'),
  ('Jake Freed', 'Inglorious Basterds'),
  ('AJ Weine', 'The Pericles'),
  ('Brandon Frankel', 'Nick Folk'),
  ('Aiden Foreman', 'Aiden''s Fantasy Football Team'),
  ('Frank Carris', 'Lumpy Churro'),
  ('Ethan Pestine', 'The Squarebutts'),
  ('Justin Tumpowsky', 'Thug Naysh'),
  ('Brandon Turofsky', 'Zay Magic')
) as v(manager_name, team_name)
join managers m on m.name = v.manager_name
cross join (select id from seasons where year = 2026) s
on conflict (season_id, manager_id) do update set team_name = excluded.team_name;

-- 4. Players (no-op if a player with this exact name already exists)
insert into players (name, position)
select v.name, v.position from (values
  ('A.J. Brown', 'WR'),
  ('Aaron Jones Sr.', 'RB'),
  ('Alec Pierce', 'WR'),
  ('Alvin Kamara', 'RB'),
  ('Amon-Ra St. Brown', 'WR'),
  ('Ashton Jeanty', 'RB'),
  ('Baker Mayfield', 'QB'),
  ('Bhayshul Tuten', 'RB'),
  ('Bijan Robinson', 'RB'),
  ('Blake Corum', 'RB'),
  ('Bo Nix', 'QB'),
  ('Braelon Allen', 'RB'),
  ('Brandon Aubrey', 'K'),
  ('Breece Hall', 'RB'),
  ('Brenton Strange', 'TE'),
  ('Brian Robinson Jr.', 'RB'),
  ('Brian Thomas Jr.', 'WR'),
  ('Brock Bowers', 'TE'),
  ('Brock Purdy', 'QB'),
  ('Bucky Irving', 'RB'),
  ('Cairo Santos', 'K'),
  ('Caleb Williams', 'QB'),
  ('Cam Little', 'K'),
  ('Cam Skattebo', 'RB'),
  ('Cam Ward', 'QB'),
  ('Cameron Dicker', 'K'),
  ('Carnell Tate', 'WR'),
  ('CeeDee Lamb', 'WR'),
  ('Chase Brown', 'RB'),
  ('Chris Godwin Jr.', 'WR'),
  ('Chris Olave', 'WR'),
  ('Chris Rodriguez Jr.', 'RB'),
  ('Christian McCaffrey', 'RB'),
  ('Christian Watson', 'WR'),
  ('Chuba Hubbard', 'RB'),
  ('Colston Loveland', 'TE'),
  ('Courtland Sutton', 'WR'),
  ('D''Andre Swift', 'RB'),
  ('DJ Moore', 'WR'),
  ('DK Metcalf', 'WR'),
  ('Dak Prescott', 'QB'),
  ('Dallas Goedert', 'TE'),
  ('Dalton Kincaid', 'TE'),
  ('Davante Adams', 'WR'),
  ('David Montgomery', 'RB'),
  ('De''Von Achane', 'RB'),
  ('De''Zhaun Stribling', 'WR'),
  ('DeVonta Smith', 'WR'),
  ('Deebo Samuel Sr.', 'WR'),
  ('Derrick Henry', 'RB'),
  ('Dontayvion Wicks', 'WR'),
  ('Drake London', 'WR'),
  ('Drake Maye', 'QB'),
  ('Dylan Sampson', 'RB'),
  ('Eddy Pineiro', 'K'),
  ('Emeka Egbuka', 'WR'),
  ('Garrett Wilson', 'WR'),
  ('George Kittle', 'TE'),
  ('George Pickens', 'WR'),
  ('Harold Fannin Jr.', 'TE'),
  ('Harrison Mevis', 'K'),
  ('Isaiah Likely', 'TE'),
  ('Isiah Pacheco', 'RB'),
  ('J.K. Dobbins', 'RB'),
  ('Ja''Marr Chase', 'WR'),
  ('Jacory Croskey-Merritt', 'RB'),
  ('Jadarian Price', 'RB'),
  ('Jahmyr Gibbs', 'RB'),
  ('Jake Bates', 'K'),
  ('Jake Ferguson', 'TE'),
  ('Jakobi Meyers', 'WR'),
  ('Jalen Coker', 'WR'),
  ('Jalen Hurts', 'QB'),
  ('James Cook III', 'RB'),
  ('Jameson Williams', 'WR'),
  ('Jared Goff', 'QB'),
  ('Jason Myers', 'K'),
  ('Javonte Williams', 'RB'),
  ('Jaxon Smith-Njigba', 'WR'),
  ('Jaxson Dart', 'QB'),
  ('Jayden Daniels', 'QB'),
  ('Jayden Reed', 'WR'),
  ('Jaylen Waddle', 'WR'),
  ('Jaylen Warren', 'RB'),
  ('Jeremiyah Love', 'RB'),
  ('Joe Burrow', 'QB'),
  ('Jonah Coleman', 'RB'),
  ('Jonathan Taylor', 'RB'),
  ('Jonathon Brooks', 'RB'),
  ('Jordan Addison', 'WR'),
  ('Jordan Mason', 'RB'),
  ('Jordyn Tyson', 'WR'),
  ('Josh Allen', 'QB'),
  ('Josh Downs', 'WR'),
  ('Josh Jacobs', 'RB'),
  ('Justin Herbert', 'QB'),
  ('Justin Jefferson', 'WR'),
  ('KC Concepcion', 'WR'),
  ('Ka''imi Fairbairn', 'K'),
  ('Kaelon Black', 'RB'),
  ('Kenneth Walker III', 'RB'),
  ('Kenny Gainwell', 'RB'),
  ('Khalil Shakir', 'WR'),
  ('Kyle Monangai', 'RB'),
  ('Kyle Pitts Sr.', 'TE'),
  ('Kyler Murray', 'QB'),
  ('Kyren Williams', 'RB'),
  ('Ladd McConkey', 'WR'),
  ('Lamar Jackson', 'QB'),
  ('Luther Burden III', 'WR'),
  ('Makai Lemon', 'WR'),
  ('Malik Nabers', 'WR'),
  ('MarShawn Lloyd', 'RB'),
  ('Mark Andrews', 'TE'),
  ('Marvin Harrison Jr.', 'WR'),
  ('Matthew Golden', 'WR'),
  ('Matthew Stafford', 'QB'),
  ('Michael Pittman Jr.', 'WR'),
  ('Michael Wilson', 'WR'),
  ('Mike Evans', 'WR'),
  ('Nick Folk', 'K'),
  ('Nico Collins', 'WR'),
  ('Omarion Hampton', 'RB'),
  ('Parker Washington', 'WR'),
  ('Patrick Mahomes', 'QB'),
  ('Puka Nacua', 'WR'),
  ('Quentin Johnston', 'WR'),
  ('Quinshon Judkins', 'RB'),
  ('RJ Harvey', 'RB'),
  ('Rachaad White', 'RB'),
  ('Rashee Rice', 'WR'),
  ('Rhamondre Stevenson', 'RB'),
  ('Rico Dowdle', 'RB'),
  ('Rome Odunze', 'WR'),
  ('Romeo Doubs', 'WR'),
  ('Sam LaPorta', 'TE'),
  ('Saquon Barkley', 'RB'),
  ('Stefon Diggs', 'WR'),
  ('Tank Bigsby', 'RB'),
  ('Tank Dell', 'WR'),
  ('Tee Higgins', 'WR'),
  ('Terry McLaurin', 'WR'),
  ('Tetairoa McMillan', 'WR'),
  ('Tony Pollard', 'RB'),
  ('Travis Etienne Jr.', 'RB'),
  ('Travis Hunter', 'WR'),
  ('Travis Kelce', 'TE'),
  ('TreVeyon Henderson', 'RB'),
  ('Trevor Lawrence', 'QB'),
  ('Trey McBride', 'TE'),
  ('Tucker Kraft', 'TE'),
  ('Tyler Warren', 'TE'),
  ('Tyreek Hill', 'WR'),
  ('Tyrone Tracy Jr.', 'RB'),
  ('Wan''Dale Robinson', 'WR'),
  ('Will Reichard', 'K'),
  ('Woody Marks', 'RB'),
  ('Xavier Worthy', 'WR'),
  ('Zach Charbonnet', 'RB'),
  ('Zay Flowers', 'WR')
) as v(name, position)
where not exists (select 1 from players p where p.name = v.name);

-- 5. Clear and reinsert this season's roster_entries for these 10 teams
delete from roster_entries where team_id in (
  select t.id from teams t
  join seasons s on s.id = t.season_id and s.year = 2026
  join managers m on m.id = t.manager_id
  where m.name in ('AJ Weine', 'Aiden Foreman', 'Brandon Frankel', 'Brandon Turofsky', 'Danny Schechter', 'Drew Ruchim', 'Ethan Pestine', 'Frank Carris', 'Jake Freed', 'Justin Tumpowsky')
);

insert into roster_entries (player_id, team_id)
select p.id, t.id
from (values
  ('Drew Ruchim', 'Jayden Daniels'),
  ('Drew Ruchim', 'Bucky Irving'),
  ('Drew Ruchim', 'Saquon Barkley'),
  ('Drew Ruchim', 'Rashee Rice'),
  ('Drew Ruchim', 'Jaxon Smith-Njigba'),
  ('Drew Ruchim', 'Harold Fannin Jr.'),
  ('Drew Ruchim', 'Emeka Egbuka'),
  ('Drew Ruchim', 'Marvin Harrison Jr.'),
  ('Drew Ruchim', 'Harrison Mevis'),
  ('Drew Ruchim', 'Alec Pierce'),
  ('Drew Ruchim', 'Xavier Worthy'),
  ('Drew Ruchim', 'Trevor Lawrence'),
  ('Drew Ruchim', 'Tank Dell'),
  ('Drew Ruchim', 'Jalen Coker'),
  ('Drew Ruchim', 'Alvin Kamara'),
  ('Drew Ruchim', 'Tank Bigsby'),
  ('Danny Schechter', 'Justin Herbert'),
  ('Danny Schechter', 'Kyren Williams'),
  ('Danny Schechter', 'Cam Skattebo'),
  ('Danny Schechter', 'Puka Nacua'),
  ('Danny Schechter', 'Drake London'),
  ('Danny Schechter', 'Brock Bowers'),
  ('Danny Schechter', 'TreVeyon Henderson'),
  ('Danny Schechter', 'Parker Washington'),
  ('Danny Schechter', 'Cam Little'),
  ('Danny Schechter', 'J.K. Dobbins'),
  ('Danny Schechter', 'Jacory Croskey-Merritt'),
  ('Danny Schechter', 'De''Zhaun Stribling'),
  ('Danny Schechter', 'Brock Purdy'),
  ('Danny Schechter', 'Jordyn Tyson'),
  ('Danny Schechter', 'Brenton Strange'),
  ('Danny Schechter', 'Kaelon Black'),
  ('Jake Freed', 'Josh Allen'),
  ('Jake Freed', 'Christian McCaffrey'),
  ('Jake Freed', 'Kenneth Walker III'),
  ('Jake Freed', 'Jaylen Waddle'),
  ('Jake Freed', 'Luther Burden III'),
  ('Jake Freed', 'Travis Kelce'),
  ('Jake Freed', 'D''Andre Swift'),
  ('Jake Freed', 'Mike Evans'),
  ('Jake Freed', 'Ka''imi Fairbairn'),
  ('Jake Freed', 'Christian Watson'),
  ('Jake Freed', 'Brian Thomas Jr.'),
  ('Jake Freed', 'Jordan Mason'),
  ('Jake Freed', 'KC Concepcion'),
  ('Jake Freed', 'Rachaad White'),
  ('Jake Freed', 'MarShawn Lloyd'),
  ('Jake Freed', 'Chris Rodriguez Jr.'),
  ('AJ Weine', 'Dak Prescott'),
  ('AJ Weine', 'Breece Hall'),
  ('AJ Weine', 'Bijan Robinson'),
  ('AJ Weine', 'George Pickens'),
  ('AJ Weine', 'Malik Nabers'),
  ('AJ Weine', 'George Kittle'),
  ('AJ Weine', 'Tee Higgins'),
  ('AJ Weine', 'David Montgomery'),
  ('AJ Weine', 'Will Reichard'),
  ('AJ Weine', 'DJ Moore'),
  ('AJ Weine', 'RJ Harvey'),
  ('AJ Weine', 'Quentin Johnston'),
  ('AJ Weine', 'Bo Nix'),
  ('AJ Weine', 'Dalton Kincaid'),
  ('AJ Weine', 'Brian Robinson Jr.'),
  ('AJ Weine', 'Braelon Allen'),
  ('Brandon Frankel', 'Drake Maye'),
  ('Brandon Frankel', 'James Cook III'),
  ('Brandon Frankel', 'De''Von Achane'),
  ('Brandon Frankel', 'Nico Collins'),
  ('Brandon Frankel', 'DeVonta Smith'),
  ('Brandon Frankel', 'Tyler Warren'),
  ('Brandon Frankel', 'Jameson Williams'),
  ('Brandon Frankel', 'Jaylen Warren'),
  ('Brandon Frankel', 'Jake Bates'),
  ('Brandon Frankel', 'Tony Pollard'),
  ('Brandon Frankel', 'Chuba Hubbard'),
  ('Brandon Frankel', 'Wan''Dale Robinson'),
  ('Brandon Frankel', 'Jayden Reed'),
  ('Brandon Frankel', 'Romeo Doubs'),
  ('Brandon Frankel', 'Kyler Murray'),
  ('Brandon Frankel', 'Chris Godwin Jr.'),
  ('Aiden Foreman', 'Lamar Jackson'),
  ('Aiden Foreman', 'Omarion Hampton'),
  ('Aiden Foreman', 'Jeremiyah Love'),
  ('Aiden Foreman', 'Amon-Ra St. Brown'),
  ('Aiden Foreman', 'Ladd McConkey'),
  ('Aiden Foreman', 'Kyle Pitts Sr.'),
  ('Aiden Foreman', 'Bhayshul Tuten'),
  ('Aiden Foreman', 'Carnell Tate'),
  ('Aiden Foreman', 'Jason Myers'),
  ('Aiden Foreman', 'Michael Wilson'),
  ('Aiden Foreman', 'Kenny Gainwell'),
  ('Aiden Foreman', 'Jake Ferguson'),
  ('Aiden Foreman', 'Deebo Samuel Sr.'),
  ('Aiden Foreman', 'Dontayvion Wicks'),
  ('Aiden Foreman', 'Jonah Coleman'),
  ('Aiden Foreman', 'Jaxson Dart'),
  ('Frank Carris', 'Matthew Stafford'),
  ('Frank Carris', 'Chase Brown'),
  ('Frank Carris', 'Javonte Williams'),
  ('Frank Carris', 'Ja''Marr Chase'),
  ('Frank Carris', 'Zay Flowers'),
  ('Frank Carris', 'Trey McBride'),
  ('Frank Carris', 'Rome Odunze'),
  ('Frank Carris', 'Jadarian Price'),
  ('Frank Carris', 'Brandon Aubrey'),
  ('Frank Carris', 'Rhamondre Stevenson'),
  ('Frank Carris', 'Travis Hunter'),
  ('Frank Carris', 'Dallas Goedert'),
  ('Frank Carris', 'Khalil Shakir'),
  ('Frank Carris', 'Nick Folk'),
  ('Frank Carris', 'Cam Ward'),
  ('Frank Carris', 'Zach Charbonnet'),
  ('Ethan Pestine', 'Joe Burrow'),
  ('Ethan Pestine', 'Jonathan Taylor'),
  ('Ethan Pestine', 'Quinshon Judkins'),
  ('Ethan Pestine', 'Justin Jefferson'),
  ('Ethan Pestine', 'Chris Olave'),
  ('Ethan Pestine', 'Tucker Kraft'),
  ('Ethan Pestine', 'Tetairoa McMillan'),
  ('Ethan Pestine', 'Jonathon Brooks'),
  ('Ethan Pestine', 'Cameron Dicker'),
  ('Ethan Pestine', 'Makai Lemon'),
  ('Ethan Pestine', 'Rico Dowdle'),
  ('Ethan Pestine', 'Jordan Addison'),
  ('Ethan Pestine', 'Josh Downs'),
  ('Ethan Pestine', 'Mark Andrews'),
  ('Ethan Pestine', 'Baker Mayfield'),
  ('Ethan Pestine', 'Dylan Sampson'),
  ('Justin Tumpowsky', 'Caleb Williams'),
  ('Justin Tumpowsky', 'Jahmyr Gibbs'),
  ('Justin Tumpowsky', 'Derrick Henry'),
  ('Justin Tumpowsky', 'A.J. Brown'),
  ('Justin Tumpowsky', 'Davante Adams'),
  ('Justin Tumpowsky', 'Colston Loveland'),
  ('Justin Tumpowsky', 'Terry McLaurin'),
  ('Justin Tumpowsky', 'Michael Pittman Jr.'),
  ('Justin Tumpowsky', 'Cairo Santos'),
  ('Justin Tumpowsky', 'Kyle Monangai'),
  ('Justin Tumpowsky', 'Aaron Jones Sr.'),
  ('Justin Tumpowsky', 'Matthew Golden'),
  ('Justin Tumpowsky', 'Isiah Pacheco'),
  ('Justin Tumpowsky', 'Stefon Diggs'),
  ('Justin Tumpowsky', 'Tyreek Hill'),
  ('Justin Tumpowsky', 'Jared Goff'),
  ('Brandon Turofsky', 'Jalen Hurts'),
  ('Brandon Turofsky', 'Ashton Jeanty'),
  ('Brandon Turofsky', 'Josh Jacobs'),
  ('Brandon Turofsky', 'CeeDee Lamb'),
  ('Brandon Turofsky', 'Garrett Wilson'),
  ('Brandon Turofsky', 'Sam LaPorta'),
  ('Brandon Turofsky', 'Travis Etienne Jr.'),
  ('Brandon Turofsky', 'Courtland Sutton'),
  ('Brandon Turofsky', 'Eddy Pineiro'),
  ('Brandon Turofsky', 'DK Metcalf'),
  ('Brandon Turofsky', 'Blake Corum'),
  ('Brandon Turofsky', 'Isaiah Likely'),
  ('Brandon Turofsky', 'Patrick Mahomes'),
  ('Brandon Turofsky', 'Jakobi Meyers'),
  ('Brandon Turofsky', 'Woody Marks'),
  ('Brandon Turofsky', 'Tyrone Tracy Jr.')
) as v(manager_name, player_name)
join managers m on m.name = v.manager_name
join teams t on t.manager_id = m.id
join seasons s on s.id = t.season_id and s.year = 2026
join players p on p.name = v.player_name;
