-- ICWT 2026-27 Week 1 per-player projections, from ESPN roster pages.
-- Stored as roster_entries.stats->'proj'->'1' so lib/predictions.js's
-- projectedWeekScore() can build real Week 1 forward lines instead of
-- treating Week 1 as a coin flip. Safe to re-run.
--
-- Builds the nested {proj: {1: ...}} object with || merges rather than
-- jsonb_set(), since jsonb_set only creates the *last* segment of a path
-- when missing -- with existing stats of '{}' (no 'proj' key at all) it
-- silently no-ops on a multi-level path like '{proj,1}' instead of erroring,
-- which is exactly what happened the first time through.

with proj_data (manager_name, player_name, proj) as (
  values
    ('Drew Ruchim', 'Jayden Daniels', 18.9),
    ('Drew Ruchim', 'Bucky Irving', 11.8),
    ('Drew Ruchim', 'Saquon Barkley', 17.0),
    ('Drew Ruchim', 'Rashee Rice', 13.8),
    ('Drew Ruchim', 'Jaxon Smith-Njigba', 17.6),
    ('Drew Ruchim', 'Harold Fannin Jr.', 9.9),
    ('Drew Ruchim', 'Emeka Egbuka', 13.4),
    ('Drew Ruchim', 'Marvin Harrison Jr.', 10.7),
    ('Drew Ruchim', 'Harrison Mevis', 9.8),
    ('Drew Ruchim', 'Alec Pierce', 10.2),
    ('Drew Ruchim', 'Xavier Worthy', 9.0),
    ('Drew Ruchim', 'Trevor Lawrence', 19.9),
    ('Drew Ruchim', 'Tank Dell', 8.9),
    ('Drew Ruchim', 'Jalen Coker', 8.1),
    ('Drew Ruchim', 'Alvin Kamara', 0.0),
    ('Drew Ruchim', 'Tank Bigsby', 4.2),
    ('Danny Schechter', 'Justin Herbert', 22.8),
    ('Danny Schechter', 'Kyren Williams', 13.1),
    ('Danny Schechter', 'Cam Skattebo', 13.1),
    ('Danny Schechter', 'Puka Nacua', 19.8),
    ('Danny Schechter', 'Drake London', 13.8),
    ('Danny Schechter', 'Brock Bowers', 14.2),
    ('Danny Schechter', 'TreVeyon Henderson', 9.4),
    ('Danny Schechter', 'Parker Washington', 10.1),
    ('Danny Schechter', 'Cam Little', 9.2),
    ('Danny Schechter', 'J.K. Dobbins', 9.1),
    ('Danny Schechter', 'Jacory Croskey-Merritt', 8.0),
    ('Danny Schechter', 'De''Zhaun Stribling', 7.5),
    ('Danny Schechter', 'Brock Purdy', 18.1),
    ('Danny Schechter', 'Jordyn Tyson', 0.0),
    ('Danny Schechter', 'Brenton Strange', 7.4),
    ('Danny Schechter', 'Kaelon Black', 3.0),
    ('Jake Freed', 'Josh Allen', 21.8),
    ('Jake Freed', 'Christian McCaffrey', 17.3),
    ('Jake Freed', 'Kenneth Walker III', 13.9),
    ('Jake Freed', 'Jaylen Waddle', 11.3),
    ('Jake Freed', 'Luther Burden III', 11.2),
    ('Jake Freed', 'Travis Kelce', 8.8),
    ('Jake Freed', 'D''Andre Swift', 12.1),
    ('Jake Freed', 'Mike Evans', 10.8),
    ('Jake Freed', 'Ka''imi Fairbairn', 10.2),
    ('Jake Freed', 'Christian Watson', 10.3),
    ('Jake Freed', 'Brian Thomas Jr.', 9.6),
    ('Jake Freed', 'Jordan Mason', 8.4),
    ('Jake Freed', 'KC Concepcion', 8.3),
    ('Jake Freed', 'Rachaad White', 8.1),
    ('Jake Freed', 'MarShawn Lloyd', 4.7),
    ('Jake Freed', 'Chris Rodriguez Jr.', 4.3),
    ('AJ Weine', 'Dak Prescott', 20.7),
    ('AJ Weine', 'Breece Hall', 15.7),
    ('AJ Weine', 'Bijan Robinson', 18.1),
    ('AJ Weine', 'George Pickens', 13.3),
    ('AJ Weine', 'Malik Nabers', 13.9),
    ('AJ Weine', 'George Kittle', 0.0),
    ('AJ Weine', 'Tee Higgins', 12.2),
    ('AJ Weine', 'David Montgomery', 11.6),
    ('AJ Weine', 'Will Reichard', 8.8),
    ('AJ Weine', 'DJ Moore', 10.9),
    ('AJ Weine', 'RJ Harvey', 7.6),
    ('AJ Weine', 'Quentin Johnston', 9.9),
    ('AJ Weine', 'Bo Nix', 18.9),
    ('AJ Weine', 'Dalton Kincaid', 7.9),
    ('AJ Weine', 'Brian Robinson Jr.', 4.8),
    ('AJ Weine', 'Braelon Allen', 4.4),
    ('Brandon Frankel', 'Drake Maye', 18.6),
    ('Brandon Frankel', 'James Cook III', 14.3),
    ('Brandon Frankel', 'De''Von Achane', 17.2),
    ('Brandon Frankel', 'Nico Collins', 14.7),
    ('Brandon Frankel', 'DeVonta Smith', 13.7),
    ('Brandon Frankel', 'Tyler Warren', 11.0),
    ('Brandon Frankel', 'Jameson Williams', 11.6),
    ('Brandon Frankel', 'Jaylen Warren', 11.7),
    ('Brandon Frankel', 'Jake Bates', 9.1),
    ('Brandon Frankel', 'Tony Pollard', 11.0),
    ('Brandon Frankel', 'Chuba Hubbard', 9.9),
    ('Brandon Frankel', 'Wan''Dale Robinson', 9.3),
    ('Brandon Frankel', 'Jayden Reed', 9.1),
    ('Brandon Frankel', 'Romeo Doubs', 7.6),
    ('Brandon Frankel', 'Kyler Murray', 18.9),
    ('Brandon Frankel', 'Chris Godwin Jr.', 8.9),
    ('Aiden Foreman', 'Lamar Jackson', 22.2),
    ('Aiden Foreman', 'Omarion Hampton', 16.7),
    ('Aiden Foreman', 'Jeremiyah Love', 15.1),
    ('Aiden Foreman', 'Amon-Ra St. Brown', 17.4),
    ('Aiden Foreman', 'Ladd McConkey', 12.9),
    ('Aiden Foreman', 'Kyle Pitts Sr.', 9.2),
    ('Aiden Foreman', 'Bhayshul Tuten', 11.8),
    ('Aiden Foreman', 'Carnell Tate', 11.2),
    ('Aiden Foreman', 'Jason Myers', 9.8),
    ('Aiden Foreman', 'Michael Wilson', 9.5),
    ('Aiden Foreman', 'Kenny Gainwell', 9.8),
    ('Aiden Foreman', 'Jake Ferguson', 8.8),
    ('Aiden Foreman', 'Deebo Samuel Sr.', 9.0),
    ('Aiden Foreman', 'Dontayvion Wicks', 6.3),
    ('Aiden Foreman', 'Jonah Coleman', 3.8),
    ('Aiden Foreman', 'Jaxson Dart', 21.2),
    ('Frank Carris', 'Matthew Stafford', 21.7),
    ('Frank Carris', 'Chase Brown', 14.9),
    ('Frank Carris', 'Javonte Williams', 14.8),
    ('Frank Carris', 'Ja''Marr Chase', 18.6),
    ('Frank Carris', 'Zay Flowers', 13.3),
    ('Frank Carris', 'Trey McBride', 12.7),
    ('Frank Carris', 'Rome Odunze', 12.1),
    ('Frank Carris', 'Jadarian Price', 13.2),
    ('Frank Carris', 'Brandon Aubrey', 10.5),
    ('Frank Carris', 'Rhamondre Stevenson', 9.8),
    ('Frank Carris', 'Travis Hunter', 6.0),
    ('Frank Carris', 'Dallas Goedert', 9.9),
    ('Frank Carris', 'Khalil Shakir', 8.5),
    ('Frank Carris', 'Nick Folk', 8.1),
    ('Frank Carris', 'Cam Ward', 15.8),
    ('Frank Carris', 'Zach Charbonnet', 0.0),
    ('Ethan Pestine', 'Joe Burrow', 22.2),
    ('Ethan Pestine', 'Jonathan Taylor', 16.9),
    ('Ethan Pestine', 'Quinshon Judkins', 12.6),
    ('Ethan Pestine', 'Justin Jefferson', 15.8),
    ('Ethan Pestine', 'Chris Olave', 13.7),
    ('Ethan Pestine', 'Tucker Kraft', 9.6),
    ('Ethan Pestine', 'Tetairoa McMillan', 13.5),
    ('Ethan Pestine', 'Jonathon Brooks', 9.9),
    ('Ethan Pestine', 'Cameron Dicker', 10.7),
    ('Ethan Pestine', 'Makai Lemon', 9.0),
    ('Ethan Pestine', 'Rico Dowdle', 11.8),
    ('Ethan Pestine', 'Jordan Addison', 9.2),
    ('Ethan Pestine', 'Josh Downs', 8.1),
    ('Ethan Pestine', 'Mark Andrews', 9.3),
    ('Ethan Pestine', 'Baker Mayfield', 19.3),
    ('Ethan Pestine', 'Dylan Sampson', 4.5),
    ('Justin Tumpowsky', 'Caleb Williams', 19.7),
    ('Justin Tumpowsky', 'Jahmyr Gibbs', 20.5),
    ('Justin Tumpowsky', 'Derrick Henry', 15.8),
    ('Justin Tumpowsky', 'A.J. Brown', 12.7),
    ('Justin Tumpowsky', 'Davante Adams', 13.2),
    ('Justin Tumpowsky', 'Colston Loveland', 11.1),
    ('Justin Tumpowsky', 'Terry McLaurin', 11.4),
    ('Justin Tumpowsky', 'Michael Pittman Jr.', 11.1),
    ('Justin Tumpowsky', 'Cairo Santos', 8.7),
    ('Justin Tumpowsky', 'Kyle Monangai', 10.1),
    ('Justin Tumpowsky', 'Aaron Jones Sr.', 9.5),
    ('Justin Tumpowsky', 'Matthew Golden', 10.0),
    ('Justin Tumpowsky', 'Isiah Pacheco', 7.0),
    ('Justin Tumpowsky', 'Stefon Diggs', 8.1),
    ('Justin Tumpowsky', 'Jared Goff', 19.3),
    ('Brandon Turofsky', 'Jalen Hurts', 24.4),
    ('Brandon Turofsky', 'Ashton Jeanty', 18.9),
    ('Brandon Turofsky', 'Josh Jacobs', 14.4),
    ('Brandon Turofsky', 'CeeDee Lamb', 16.3),
    ('Brandon Turofsky', 'Garrett Wilson', 13.4),
    ('Brandon Turofsky', 'Sam LaPorta', 9.9),
    ('Brandon Turofsky', 'Travis Etienne Jr.', 14.1),
    ('Brandon Turofsky', 'Courtland Sutton', 10.9),
    ('Brandon Turofsky', 'Eddy Pineiro', 9.1),
    ('Brandon Turofsky', 'DK Metcalf', 11.6),
    ('Brandon Turofsky', 'Blake Corum', 9.1),
    ('Brandon Turofsky', 'Isaiah Likely', 8.5),
    ('Brandon Turofsky', 'Patrick Mahomes', 18.1),
    ('Brandon Turofsky', 'Jakobi Meyers', 9.6),
    ('Brandon Turofsky', 'Woody Marks', 7.6),
    ('Brandon Turofsky', 'Tyrone Tracy Jr.', 3.7)
),
resolved as (
  select re.id as roster_entry_id, pd.proj
  from proj_data pd
  join managers m on m.name = pd.manager_name
  join teams t on t.manager_id = m.id
  join seasons s on s.id = t.season_id and s.year = 2026
  join players p on p.name = pd.player_name
  join roster_entries re on re.team_id = t.id and re.player_id = p.id
)
update roster_entries
set stats = coalesce(roster_entries.stats, '{}'::jsonb)
  || jsonb_build_object(
       'proj',
       coalesce(roster_entries.stats -> 'proj', '{}'::jsonb) || jsonb_build_object('1', resolved.proj)
     )
from resolved
where roster_entries.id = resolved.roster_entry_id;
